#devpanel
#Copyright (C) 2018 devpanel

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.



AWSTemplateFormatVersion: 2010-09-09
Description: Sets up drupal
Parameters:
  ClusterName:
    Type: String

  HostedZoneName:
    Type: String

  LoadBalancerCname:
    Type: String

  TypeProject:
    Type: String

Resources:
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${HostedZoneName}
      RecordSets:
        - Name: !Sub ${LoadBalancerCname}
          Type: A
          AliasTarget:
              DNSName:
                'Fn::ImportValue': !Sub '${ClusterName}BackendAlbDns'
              HostedZoneId:
                'Fn::ImportValue': !Sub '${ClusterName}CanonicalAlbHostedZoneID'
